# Generated by Django 5.0.4 on 2024-04-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_remove_livros_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acervolivrosusuarios',
            options={'verbose_name': 'AcervoLivrosUsuario', 'verbose_name_plural': 'AcervoLivrosUsuarios'},
        ),
        migrations.AlterModelOptions(
            name='autores',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editoras',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
    ]
